### ISSUE TITLE
Test loftr in inloc

### ISSUE THREAD

**Issue by xunfeng2zkj** [GrumpyZhou/image-matching-toolbox#38]
hi，i used image-matching-toolbox to eval loftr for inloc, 
config:
default: &default
    class: 'LoFTR'
    ckpt: 'pretrained/loftr/outdoor_ds.ckpt'
    match_threshold: 0.2
    imsize: 1024
    no_match_upscale: False
example:
    <<: *default
    match_threshold: 0.5
    imsize: -1
hpatch:
    <<: *default
    imsize: 480
    no_match_upscale: True
inloc:
    <<: *default
    pairs: 'pairs-query-netvlad40-temporal.txt'
    rthres: 48
    skip_matches: 20

and then get result as below:
![image](https://user-images.githubusercontent.com/22878414/195819108-eb7da6b2-2d0c-436d-8666-6aec5fa2179c.png)

**Comment by GrumpyZhou** [comment]
Hi @xunfeng2zkj ,

Could you detail what  your issue is?

**Comment by xunfeng2zkj** [comment]
Can I cite this result and this repo in my paper？

**Comment by GrumpyZhou** [comment]
@xunfeng2zkj ,

Do you mean for Loftr? I think in the original paper, they are not using this repo, so I would rather stick to the paper numbers to compare it Loftr on InLoc.

Regarding citation, if you use it to run your own methods, yes you can cite this repo.

On the other hand, I remember I have obtained better results for LoFTR using this repo :
(48.5 / 73.2 / 83.8 | 55.0 / 75.6 / 83.2)

Can you try with the config I used:
```
inloc:
    <<: *default
    match_threshold: 0.5
    npts: 4096
    imsize: 1024
    pairs: 'pairs-query-netvlad40-temporal.txt'
    rthres: 48
    skip_matches: 20
```
