### ISSUE TITLE
FileNotFoundError: no 'cameras.bin' when test loftr on aachen

### ISSUE THREAD

**Issue by Master-cai** [GrumpyZhou/image-matching-toolbox#50]
Hi, I use your default code and yml to test loftr on aachen benchmark as follow:
`python -m immatch.eval_aachen --gpu 1 --config 'loftr' --colmap /usr/bin/colmap --benchmark_name 'aachen'`
After running for a dozen hours, I met this error:
```
runpy.py 194 _run_module_as_main
return _run_code(code, main_globals, None,

runpy.py 87 _run_code
exec(code, run_globals)

eval_aachen.py 84 <module>
eval_aachen(args)

eval_aachen.py 56 eval_aachen
reconstruct_database_pairs(args)

localize_sfm_helper.py 107 reconstruct_database_pairs
triangulation.main(

triangulation.py 180 main
image_ids = create_db_from_model(empty_sfm_model, database)

triangulation.py 22 create_db_from_model
cameras = read_cameras_binary(str(empty_model / 'cameras.bin'))

read_write_model.py 135 read_cameras_binary
with open(path_to_model_file, "rb") as fid:

FileNotFoundError:
2
No such file or directory
outputs/aachen/empty_sfm/cameras.bin
```
the specific config is:
```yml
aachen:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    npts: 4096
    imsize: 1024
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: True
```
I have no idea what`s going on, can u give me some advice? thank!
@GrumpyZhou
