### ISSUE TITLE
The loftr config

### ISSUE THREAD

**Issue by boyagesmile** [GrumpyZhou/image-matching-toolbox#59]
```
aachen:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    npts: 4096
    imsize: 1024
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: True
```
what's the meaning of "npts"? the number of point?But I didn't see the call
